// Generated by src/build.py — do not edit by hand.
window.CAMPAIGN = {
  "client": "BIMC CosMedic",
  "campaign": "Generic Display Ads",
  "platform": "The Trade Desk · HTML5",
  "updated": "2026-10-09",
  "revision": "v5 · revision brief 1 Oct + review 9 Oct 2026",
  "clickTag": "clickTAG",
  "logo": "preview/logo.svg",
  "packages": [
    {
      "label": "Statics for News Corp, all frames",
      "path": "deliverables/BIMC-AU-Display-Generic-v5-STATICS.zip",
      "kb": 788.0
    },
    {
      "label": "Generic V1 HTML5 · all sizes",
      "path": "deliverables/BIMC-AU-Display-GenericV1-v5-HTML5.zip",
      "kb": 380.7
    },
    {
      "label": "Generic V2 HTML5 · all sizes",
      "path": "deliverables/BIMC-AU-Display-GenericV2-v5-HTML5.zip",
      "kb": 428.3
    },
    {
      "label": "Everything",
      "path": "deliverables/BIMC-AU-Display-Generic-v5-ALL.zip",
      "kb": 1634.4
    }
  ],
  "changes": [
    "v5 · ACHS International and the Healthcare Asia Awards logo are now the same size: their lettering is matched and sits on one line, in one fixed lockup used in every ad.",
    "v4 · Accreditation logos replaced with the client's files: ACHS International and Healthcare Asia Awards 2026, side by side and large enough to read.",
    "v4 · Each ad is now one self-contained index.html (photos, logos and fonts inside, under 150 KB), so it renders correctly even when opened straight from the zip. All images are built at 2× for sharp retina display.",
    "v3 · The CosMedic logo is in the official brown (#533E27); the full logo appears in every size, including 320×50.",
    "v3 · 300×250: the photo blends into the copy with the same soft gradient as the other sizes.",
    "Both logos appear on every frame of every size and stay on screen for the whole animation.",
    "Generic V1: frame 1 keeps the team; frames 2 and 3 show people — the doctor at the bedside for “Recovery · Follow-up”, the front desk welcoming a patient for the package line.",
    "Generic V2: frame 1 keeps the lobby; frame 2 shows BIMC Nusa Dua; frame 3 the reception lobby. The photo of a surgeon marking a patient’s face is removed.",
    "No procedure on a patient and no before/after anywhere; every photo is framed per size so faces stay whole.",
    "Statics of every frame and size for News Corp, named BIMC-AU-<channel>-<asset>-<size>-v<n>."
  ],
  "previewClickUrl": "https://cosmedic.bimcbali.com/en",
  "versions": [
    {
      "id": "GEN-V1",
      "label": "Generic V1",
      "headline": "Care through every stage",
      "cta": "Learn more",
      "frames": [
        "Consultation · Planning · Procedure",
        "Recovery · Follow-up",
        "Features and inclusions vary by treatment and package."
      ],
      "ads": [
        {
          "size": "300x600",
          "width": 300,
          "height": 600,
          "name": "BIMC-AU-Display-GenericV1-300x600-v5",
          "html": "banners/GEN-V1/BIMC-AU-Display-GenericV1-300x600-v5/index.html",
          "zip": "deliverables/GEN-V1/BIMC-AU-Display-GenericV1-300x600-v5.zip",
          "backup": "deliverables/GEN-V1/BIMC-AU-Display-GenericV1-300x600-v5.jpg",
          "statics": [
            "deliverables/statics/GEN-V1/BIMC-AU-Display-GenericV1-300x600-v5-F1.jpg",
            "deliverables/statics/GEN-V1/BIMC-AU-Display-GenericV1-300x600-v5-F2.jpg",
            "deliverables/statics/GEN-V1/BIMC-AU-Display-GenericV1-300x600-v5-F3.jpg"
          ],
          "initialKB": 148.1,
          "totalKB": 148.1,
          "zipKB": 105.5,
          "htmlKB": 148.1,
          "files": 1,
          "durationS": 13.8,
          "loops": 2
        },
        {
          "size": "160x600",
          "width": 160,
          "height": 600,
          "name": "BIMC-AU-Display-GenericV1-160x600-v5",
          "html": "banners/GEN-V1/BIMC-AU-Display-GenericV1-160x600-v5/index.html",
          "zip": "deliverables/GEN-V1/BIMC-AU-Display-GenericV1-160x600-v5.zip",
          "backup": "deliverables/GEN-V1/BIMC-AU-Display-GenericV1-160x600-v5.jpg",
          "statics": [
            "deliverables/statics/GEN-V1/BIMC-AU-Display-GenericV1-160x600-v5-F1.jpg",
            "deliverables/statics/GEN-V1/BIMC-AU-Display-GenericV1-160x600-v5-F2.jpg",
            "deliverables/statics/GEN-V1/BIMC-AU-Display-GenericV1-160x600-v5-F3.jpg"
          ],
          "initialKB": 91.3,
          "totalKB": 91.3,
          "zipKB": 62.2,
          "htmlKB": 91.3,
          "files": 1,
          "durationS": 13.8,
          "loops": 2
        },
        {
          "size": "300x250",
          "width": 300,
          "height": 250,
          "name": "BIMC-AU-Display-GenericV1-300x250-v5",
          "html": "banners/GEN-V1/BIMC-AU-Display-GenericV1-300x250-v5/index.html",
          "zip": "deliverables/GEN-V1/BIMC-AU-Display-GenericV1-300x250-v5.zip",
          "backup": "deliverables/GEN-V1/BIMC-AU-Display-GenericV1-300x250-v5.jpg",
          "statics": [
            "deliverables/statics/GEN-V1/BIMC-AU-Display-GenericV1-300x250-v5-F1.jpg",
            "deliverables/statics/GEN-V1/BIMC-AU-Display-GenericV1-300x250-v5-F2.jpg",
            "deliverables/statics/GEN-V1/BIMC-AU-Display-GenericV1-300x250-v5-F3.jpg"
          ],
          "initialKB": 80.1,
          "totalKB": 80.1,
          "zipKB": 53.7,
          "htmlKB": 80.1,
          "files": 1,
          "durationS": 13.8,
          "loops": 2
        },
        {
          "size": "728x90",
          "width": 728,
          "height": 90,
          "name": "BIMC-AU-Display-GenericV1-728x90-v5",
          "html": "banners/GEN-V1/BIMC-AU-Display-GenericV1-728x90-v5/index.html",
          "zip": "deliverables/GEN-V1/BIMC-AU-Display-GenericV1-728x90-v5.zip",
          "backup": "deliverables/GEN-V1/BIMC-AU-Display-GenericV1-728x90-v5.jpg",
          "statics": [
            "deliverables/statics/GEN-V1/BIMC-AU-Display-GenericV1-728x90-v5-F1.jpg",
            "deliverables/statics/GEN-V1/BIMC-AU-Display-GenericV1-728x90-v5-F2.jpg",
            "deliverables/statics/GEN-V1/BIMC-AU-Display-GenericV1-728x90-v5-F3.jpg"
          ],
          "initialKB": 72.8,
          "totalKB": 72.8,
          "zipKB": 48.5,
          "htmlKB": 72.8,
          "files": 1,
          "durationS": 13.8,
          "loops": 2
        },
        {
          "size": "320x50",
          "width": 320,
          "height": 50,
          "name": "BIMC-AU-Display-GenericV1-320x50-v5",
          "html": "banners/GEN-V1/BIMC-AU-Display-GenericV1-320x50-v5/index.html",
          "zip": "deliverables/GEN-V1/BIMC-AU-Display-GenericV1-320x50-v5.zip",
          "backup": "deliverables/GEN-V1/BIMC-AU-Display-GenericV1-320x50-v5.jpg",
          "statics": [
            "deliverables/statics/GEN-V1/BIMC-AU-Display-GenericV1-320x50-v5-F1.jpg",
            "deliverables/statics/GEN-V1/BIMC-AU-Display-GenericV1-320x50-v5-F2.jpg",
            "deliverables/statics/GEN-V1/BIMC-AU-Display-GenericV1-320x50-v5-F3.jpg"
          ],
          "initialKB": 31.4,
          "totalKB": 31.4,
          "zipKB": 17.0,
          "htmlKB": 31.4,
          "files": 1,
          "durationS": 13.8,
          "loops": 2
        }
      ]
    },
    {
      "id": "GEN-V2",
      "label": "Generic V2",
      "headline": "BIMC CosMedic",
      "cta": "Plan your treatment",
      "frames": [
        "The care of medicine. The grace of Bali.",
        "A Cosmetic Medicine Practice Based in Nusa Dua, Bali. ACHSI-accredited.",
        "One Consultation, no obligations."
      ],
      "ads": [
        {
          "size": "300x600",
          "width": 300,
          "height": 600,
          "name": "BIMC-AU-Display-GenericV2-300x600-v5",
          "html": "banners/GEN-V2/BIMC-AU-Display-GenericV2-300x600-v5/index.html",
          "zip": "deliverables/GEN-V2/BIMC-AU-Display-GenericV2-300x600-v5.zip",
          "backup": "deliverables/GEN-V2/BIMC-AU-Display-GenericV2-300x600-v5.jpg",
          "statics": [
            "deliverables/statics/GEN-V2/BIMC-AU-Display-GenericV2-300x600-v5-F1.jpg",
            "deliverables/statics/GEN-V2/BIMC-AU-Display-GenericV2-300x600-v5-F2.jpg",
            "deliverables/statics/GEN-V2/BIMC-AU-Display-GenericV2-300x600-v5-F3.jpg"
          ],
          "initialKB": 147.6,
          "totalKB": 147.6,
          "zipKB": 105.1,
          "htmlKB": 147.6,
          "files": 1,
          "durationS": 13.8,
          "loops": 2
        },
        {
          "size": "160x600",
          "width": 160,
          "height": 600,
          "name": "BIMC-AU-Display-GenericV2-160x600-v5",
          "html": "banners/GEN-V2/BIMC-AU-Display-GenericV2-160x600-v5/index.html",
          "zip": "deliverables/GEN-V2/BIMC-AU-Display-GenericV2-160x600-v5.zip",
          "backup": "deliverables/GEN-V2/BIMC-AU-Display-GenericV2-160x600-v5.jpg",
          "statics": [
            "deliverables/statics/GEN-V2/BIMC-AU-Display-GenericV2-160x600-v5-F1.jpg",
            "deliverables/statics/GEN-V2/BIMC-AU-Display-GenericV2-160x600-v5-F2.jpg",
            "deliverables/statics/GEN-V2/BIMC-AU-Display-GenericV2-160x600-v5-F3.jpg"
          ],
          "initialKB": 135.9,
          "totalKB": 135.9,
          "zipKB": 96.2,
          "htmlKB": 135.9,
          "files": 1,
          "durationS": 13.8,
          "loops": 2
        },
        {
          "size": "300x250",
          "width": 300,
          "height": 250,
          "name": "BIMC-AU-Display-GenericV2-300x250-v5",
          "html": "banners/GEN-V2/BIMC-AU-Display-GenericV2-300x250-v5/index.html",
          "zip": "deliverables/GEN-V2/BIMC-AU-Display-GenericV2-300x250-v5.zip",
          "backup": "deliverables/GEN-V2/BIMC-AU-Display-GenericV2-300x250-v5.jpg",
          "statics": [
            "deliverables/statics/GEN-V2/BIMC-AU-Display-GenericV2-300x250-v5-F1.jpg",
            "deliverables/statics/GEN-V2/BIMC-AU-Display-GenericV2-300x250-v5-F2.jpg",
            "deliverables/statics/GEN-V2/BIMC-AU-Display-GenericV2-300x250-v5-F3.jpg"
          ],
          "initialKB": 100.3,
          "totalKB": 100.3,
          "zipKB": 69.2,
          "htmlKB": 100.3,
          "files": 1,
          "durationS": 13.8,
          "loops": 2
        },
        {
          "size": "728x90",
          "width": 728,
          "height": 90,
          "name": "BIMC-AU-Display-GenericV2-728x90-v5",
          "html": "banners/GEN-V2/BIMC-AU-Display-GenericV2-728x90-v5/index.html",
          "zip": "deliverables/GEN-V2/BIMC-AU-Display-GenericV2-728x90-v5.zip",
          "backup": "deliverables/GEN-V2/BIMC-AU-Display-GenericV2-728x90-v5.jpg",
          "statics": [
            "deliverables/statics/GEN-V2/BIMC-AU-Display-GenericV2-728x90-v5-F1.jpg",
            "deliverables/statics/GEN-V2/BIMC-AU-Display-GenericV2-728x90-v5-F2.jpg",
            "deliverables/statics/GEN-V2/BIMC-AU-Display-GenericV2-728x90-v5-F3.jpg"
          ],
          "initialKB": 82.0,
          "totalKB": 82.0,
          "zipKB": 55.4,
          "htmlKB": 82.0,
          "files": 1,
          "durationS": 13.8,
          "loops": 2
        },
        {
          "size": "320x50",
          "width": 320,
          "height": 50,
          "name": "BIMC-AU-Display-GenericV2-320x50-v5",
          "html": "banners/GEN-V2/BIMC-AU-Display-GenericV2-320x50-v5/index.html",
          "zip": "deliverables/GEN-V2/BIMC-AU-Display-GenericV2-320x50-v5.zip",
          "backup": "deliverables/GEN-V2/BIMC-AU-Display-GenericV2-320x50-v5.jpg",
          "statics": [
            "deliverables/statics/GEN-V2/BIMC-AU-Display-GenericV2-320x50-v5-F1.jpg",
            "deliverables/statics/GEN-V2/BIMC-AU-Display-GenericV2-320x50-v5-F2.jpg",
            "deliverables/statics/GEN-V2/BIMC-AU-Display-GenericV2-320x50-v5-F3.jpg"
          ],
          "initialKB": 32.4,
          "totalKB": 32.4,
          "zipKB": 17.9,
          "htmlKB": 32.4,
          "files": 1,
          "durationS": 13.8,
          "loops": 2
        }
      ]
    }
  ]
};
