// Generated by src/build.py — do not edit by hand.
window.CAMPAIGN = {
  "client": "BIMC CosMedic",
  "campaign": "Generic Display Ads",
  "platform": "The Trade Desk · HTML5",
  "updated": "2026-10-09",
  "revision": "v2 · client revision brief, 1 Oct 2026",
  "clickTag": "clickTAG",
  "logo": "preview/logo.svg",
  "packages": [
    {
      "label": "Statics for News Corp, all frames",
      "path": "deliverables/BIMC-AU-Display-Generic-v2-STATICS.zip",
      "kb": 812.2
    },
    {
      "label": "Generic V1 HTML5 · all sizes",
      "path": "deliverables/BIMC-AU-Display-GenericV1-v2-HTML5.zip",
      "kb": 571.6
    },
    {
      "label": "Generic V2 HTML5 · all sizes",
      "path": "deliverables/BIMC-AU-Display-GenericV2-v2-HTML5.zip",
      "kb": 653.9
    },
    {
      "label": "Everything",
      "path": "deliverables/BIMC-AU-Display-Generic-v2-ALL.zip",
      "kb": 2078.3
    }
  ],
  "changes": [
    "ACHS International and Healthcare Asia Awards 2026 lockup on every frame of every size (compact on 728×90 and 320×50); it stays on screen for the whole animation.",
    "Generic V1: frame 1 keeps the team; frames 2 and 3 now show people — the doctor at the bedside for “Recovery · Follow-up”, the front desk welcoming a patient for the package line.",
    "Generic V2: frame 1 keeps the lobby; frame 2 shows BIMC Nusa Dua; frame 3 the reception lobby. The photo of a surgeon marking a patient’s face is removed.",
    "No procedure on a patient and no before/after anywhere. Every photo is re-framed per size so faces stay whole and nothing feels cramped.",
    "Statics of every frame and size for News Corp, named BIMC-AU-<channel>-<asset>-<size>-v<n>."
  ],
  "previewClickUrl": "https://cosmedic.bimcbali.com/en",
  "versions": [
    {
      "id": "GEN-V1",
      "label": "Generic V1",
      "headline": "Care through every stage",
      "cta": "Learn more",
      "frames": [
        "Consultation · Planning · Procedure",
        "Recovery · Follow-up",
        "Features and inclusions vary by treatment and package."
      ],
      "ads": [
        {
          "size": "300x600",
          "width": 300,
          "height": 600,
          "name": "BIMC-AU-Display-GenericV1-300x600-v2",
          "html": "banners/GEN-V1/BIMC-AU-Display-GenericV1-300x600-v2/index.html",
          "zip": "deliverables/GEN-V1/BIMC-AU-Display-GenericV1-300x600-v2.zip",
          "backup": "deliverables/GEN-V1/BIMC-AU-Display-GenericV1-300x600-v2.jpg",
          "statics": [
            "deliverables/statics/GEN-V1/BIMC-AU-Display-GenericV1-300x600-v2-F1.jpg",
            "deliverables/statics/GEN-V1/BIMC-AU-Display-GenericV1-300x600-v2-F2.jpg",
            "deliverables/statics/GEN-V1/BIMC-AU-Display-GenericV1-300x600-v2-F3.jpg"
          ],
          "initialKB": 94.1,
          "totalKB": 198.1,
          "zipKB": 183.3,
          "htmlKB": 29.0,
          "files": 5,
          "durationS": 13.8,
          "loops": 2
        },
        {
          "size": "160x600",
          "width": 160,
          "height": 600,
          "name": "BIMC-AU-Display-GenericV1-160x600-v2",
          "html": "banners/GEN-V1/BIMC-AU-Display-GenericV1-160x600-v2/index.html",
          "zip": "deliverables/GEN-V1/BIMC-AU-Display-GenericV1-160x600-v2.zip",
          "backup": "deliverables/GEN-V1/BIMC-AU-Display-GenericV1-160x600-v2.jpg",
          "statics": [
            "deliverables/statics/GEN-V1/BIMC-AU-Display-GenericV1-160x600-v2-F1.jpg",
            "deliverables/statics/GEN-V1/BIMC-AU-Display-GenericV1-160x600-v2-F2.jpg",
            "deliverables/statics/GEN-V1/BIMC-AU-Display-GenericV1-160x600-v2-F3.jpg"
          ],
          "initialKB": 71.6,
          "totalKB": 124.1,
          "zipKB": 109.4,
          "htmlKB": 29.1,
          "files": 5,
          "durationS": 13.8,
          "loops": 2
        },
        {
          "size": "300x250",
          "width": 300,
          "height": 250,
          "name": "BIMC-AU-Display-GenericV1-300x250-v2",
          "html": "banners/GEN-V1/BIMC-AU-Display-GenericV1-300x250-v2/index.html",
          "zip": "deliverables/GEN-V1/BIMC-AU-Display-GenericV1-300x250-v2.zip",
          "backup": "deliverables/GEN-V1/BIMC-AU-Display-GenericV1-300x250-v2.jpg",
          "statics": [
            "deliverables/statics/GEN-V1/BIMC-AU-Display-GenericV1-300x250-v2-F1.jpg",
            "deliverables/statics/GEN-V1/BIMC-AU-Display-GenericV1-300x250-v2-F2.jpg",
            "deliverables/statics/GEN-V1/BIMC-AU-Display-GenericV1-300x250-v2-F3.jpg"
          ],
          "initialKB": 60.3,
          "totalKB": 92.3,
          "zipKB": 77.7,
          "htmlKB": 29.0,
          "files": 5,
          "durationS": 13.8,
          "loops": 2
        },
        {
          "size": "728x90",
          "width": 728,
          "height": 90,
          "name": "BIMC-AU-Display-GenericV1-728x90-v2",
          "html": "banners/GEN-V1/BIMC-AU-Display-GenericV1-728x90-v2/index.html",
          "zip": "deliverables/GEN-V1/BIMC-AU-Display-GenericV1-728x90-v2.zip",
          "backup": "deliverables/GEN-V1/BIMC-AU-Display-GenericV1-728x90-v2.jpg",
          "statics": [
            "deliverables/statics/GEN-V1/BIMC-AU-Display-GenericV1-728x90-v2-F1.jpg",
            "deliverables/statics/GEN-V1/BIMC-AU-Display-GenericV1-728x90-v2-F2.jpg",
            "deliverables/statics/GEN-V1/BIMC-AU-Display-GenericV1-728x90-v2-F3.jpg"
          ],
          "initialKB": 54.0,
          "totalKB": 82.3,
          "zipKB": 67.7,
          "htmlKB": 29.0,
          "files": 5,
          "durationS": 13.8,
          "loops": 2
        },
        {
          "size": "320x50",
          "width": 320,
          "height": 50,
          "name": "BIMC-AU-Display-GenericV1-320x50-v2",
          "html": "banners/GEN-V1/BIMC-AU-Display-GenericV1-320x50-v2/index.html",
          "zip": "deliverables/GEN-V1/BIMC-AU-Display-GenericV1-320x50-v2.zip",
          "backup": "deliverables/GEN-V1/BIMC-AU-Display-GenericV1-320x50-v2.jpg",
          "statics": [
            "deliverables/statics/GEN-V1/BIMC-AU-Display-GenericV1-320x50-v2-F1.jpg",
            "deliverables/statics/GEN-V1/BIMC-AU-Display-GenericV1-320x50-v2-F2.jpg",
            "deliverables/statics/GEN-V1/BIMC-AU-Display-GenericV1-320x50-v2-F3.jpg"
          ],
          "initialKB": 35.6,
          "totalKB": 45.7,
          "zipKB": 37.7,
          "htmlKB": 16.8,
          "files": 5,
          "durationS": 13.8,
          "loops": 2
        }
      ]
    },
    {
      "id": "GEN-V2",
      "label": "Generic V2",
      "headline": "BIMC CosMedic",
      "cta": "Plan your treatment",
      "frames": [
        "The care of medicine. The grace of Bali.",
        "A Cosmetic Medicine Practice Based in Nusa Dua, Bali. ACHSI-accredited.",
        "One Consultation, no obligations."
      ],
      "ads": [
        {
          "size": "300x600",
          "width": 300,
          "height": 600,
          "name": "BIMC-AU-Display-GenericV2-300x600-v2",
          "html": "banners/GEN-V2/BIMC-AU-Display-GenericV2-300x600-v2/index.html",
          "zip": "deliverables/GEN-V2/BIMC-AU-Display-GenericV2-300x600-v2.zip",
          "backup": "deliverables/GEN-V2/BIMC-AU-Display-GenericV2-300x600-v2.jpg",
          "statics": [
            "deliverables/statics/GEN-V2/BIMC-AU-Display-GenericV2-300x600-v2-F1.jpg",
            "deliverables/statics/GEN-V2/BIMC-AU-Display-GenericV2-300x600-v2-F2.jpg",
            "deliverables/statics/GEN-V2/BIMC-AU-Display-GenericV2-300x600-v2-F3.jpg"
          ],
          "initialKB": 97.3,
          "totalKB": 239.3,
          "zipKB": 223.9,
          "htmlKB": 30.0,
          "files": 5,
          "durationS": 13.8,
          "loops": 2
        },
        {
          "size": "160x600",
          "width": 160,
          "height": 600,
          "name": "BIMC-AU-Display-GenericV2-160x600-v2",
          "html": "banners/GEN-V2/BIMC-AU-Display-GenericV2-160x600-v2/index.html",
          "zip": "deliverables/GEN-V2/BIMC-AU-Display-GenericV2-160x600-v2.zip",
          "backup": "deliverables/GEN-V2/BIMC-AU-Display-GenericV2-160x600-v2.jpg",
          "statics": [
            "deliverables/statics/GEN-V2/BIMC-AU-Display-GenericV2-160x600-v2-F1.jpg",
            "deliverables/statics/GEN-V2/BIMC-AU-Display-GenericV2-160x600-v2-F2.jpg",
            "deliverables/statics/GEN-V2/BIMC-AU-Display-GenericV2-160x600-v2-F3.jpg"
          ],
          "initialKB": 73.9,
          "totalKB": 156.1,
          "zipKB": 141.1,
          "htmlKB": 30.1,
          "files": 5,
          "durationS": 13.8,
          "loops": 2
        },
        {
          "size": "300x250",
          "width": 300,
          "height": 250,
          "name": "BIMC-AU-Display-GenericV2-300x250-v2",
          "html": "banners/GEN-V2/BIMC-AU-Display-GenericV2-300x250-v2/index.html",
          "zip": "deliverables/GEN-V2/BIMC-AU-Display-GenericV2-300x250-v2.zip",
          "backup": "deliverables/GEN-V2/BIMC-AU-Display-GenericV2-300x250-v2.jpg",
          "statics": [
            "deliverables/statics/GEN-V2/BIMC-AU-Display-GenericV2-300x250-v2-F1.jpg",
            "deliverables/statics/GEN-V2/BIMC-AU-Display-GenericV2-300x250-v2-F2.jpg",
            "deliverables/statics/GEN-V2/BIMC-AU-Display-GenericV2-300x250-v2-F3.jpg"
          ],
          "initialKB": 60.1,
          "totalKB": 101.7,
          "zipKB": 87.0,
          "htmlKB": 30.0,
          "files": 5,
          "durationS": 13.8,
          "loops": 2
        },
        {
          "size": "728x90",
          "width": 728,
          "height": 90,
          "name": "BIMC-AU-Display-GenericV2-728x90-v2",
          "html": "banners/GEN-V2/BIMC-AU-Display-GenericV2-728x90-v2/index.html",
          "zip": "deliverables/GEN-V2/BIMC-AU-Display-GenericV2-728x90-v2.zip",
          "backup": "deliverables/GEN-V2/BIMC-AU-Display-GenericV2-728x90-v2.jpg",
          "statics": [
            "deliverables/statics/GEN-V2/BIMC-AU-Display-GenericV2-728x90-v2-F1.jpg",
            "deliverables/statics/GEN-V2/BIMC-AU-Display-GenericV2-728x90-v2-F2.jpg",
            "deliverables/statics/GEN-V2/BIMC-AU-Display-GenericV2-728x90-v2-F3.jpg"
          ],
          "initialKB": 54.9,
          "totalKB": 89.7,
          "zipKB": 75.0,
          "htmlKB": 30.0,
          "files": 5,
          "durationS": 13.8,
          "loops": 2
        },
        {
          "size": "320x50",
          "width": 320,
          "height": 50,
          "name": "BIMC-AU-Display-GenericV2-320x50-v2",
          "html": "banners/GEN-V2/BIMC-AU-Display-GenericV2-320x50-v2/index.html",
          "zip": "deliverables/GEN-V2/BIMC-AU-Display-GenericV2-320x50-v2.zip",
          "backup": "deliverables/GEN-V2/BIMC-AU-Display-GenericV2-320x50-v2.jpg",
          "statics": [
            "deliverables/statics/GEN-V2/BIMC-AU-Display-GenericV2-320x50-v2-F1.jpg",
            "deliverables/statics/GEN-V2/BIMC-AU-Display-GenericV2-320x50-v2-F2.jpg",
            "deliverables/statics/GEN-V2/BIMC-AU-Display-GenericV2-320x50-v2-F3.jpg"
          ],
          "initialKB": 36.6,
          "totalKB": 48.2,
          "zipKB": 40.0,
          "htmlKB": 17.9,
          "files": 5,
          "durationS": 13.8,
          "loops": 2
        }
      ]
    }
  ]
};
